platform :ios, '7.0'

target 'Sparta' do
    
pod 'AFNetworking', '3.0.0'
pod 'SDWebImage', '3.7.6'
pod 'Masonry', '1.0.0'
pod 'MJRefresh', '3.1.10'
pod 'FMDB', '2.3'
pod 'YYCache', '1.0.3'
pod 'YYModel', '1.0.1'
pod 'SVProgressHUD', '2.0.3'

end
